# Generated by Django 2.1.2 on 2018-10-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(verbose_name='浏览时间')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64, verbose_name='网站')),
                ('visit_count', models.IntegerField(blank=True, default=0, verbose_name='访问次数')),
                ('last_visited_time', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
            ],
        ),
        migrations.CreateModel(
            name='WebType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='网站类型')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser_record.WebType', verbose_name='网站类型'),
        ),
        migrations.AddField(
            model_name='chromerecord',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser_record.Domain', verbose_name='域名'),
        ),
    ]
