# Generated by Django 2.1.2 on 2019-05-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='余额')),
                ('type', models.SmallIntegerField(choices=[(1, '入账'), (2, '消费')], default=2, verbose_name='变更类型')),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='变更金额')),
                ('consume_time', models.SmallIntegerField(choices=[(1, '早上'), (2, '上午'), (3, '晚上'), (4, '下午')], verbose_name='消费时间')),
                ('consume_date', models.DateField(blank=True, verbose_name='消费日期')),
                ('extra_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('is_card', models.BooleanField(default=True, verbose_name='是否是银行卡消费')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '银行卡'), (2, '微信'), (3, '支付宝'), (4, '信用卡'), (5, '现金')], default=1, verbose_name='支付方式')),
            ],
            options={
                'verbose_name': '财务变更日志',
                'verbose_name_plural': '财务变更日志',
                'ordering': ['-create_time', '-update_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='消费类型')),
            ],
        ),
        migrations.AddField(
            model_name='balancelog',
            name='consume_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.ConsumeType', verbose_name='消费类型'),
        ),
    ]
