# Generated by Django 2.1.2 on 2023-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='变更金额'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
    ]
